export default {
    ONBOARDING_SCREEN: 'Onboarding',
    LOGIN_SCREEN: "Login",
    LOGIN_FORM_SCREEN: "LoginForm",
    FORGOT_PASSWORD_SCREEN: 'ForgotPassword',
    OTP_SCREEN: "OtpScreen",
    NEW_PASSWORD_SCREEN: "NewPassword",
    RESET_SUCCESSFULLY: "PasswordResetSuccssful",
    SIGNUP_SCREEN: "Signup",
    SIGNUP_FORM_SCREEN: "SignupForm",
    PAYMENT_METHOD_SCREEN: "PaymentMethod",
    DETAILS_SCREEN: "Details",
    SET_LOCATION_SCREEN: "SetLocation",
    UPLOAD_PROFILE_PHOTO_SCREEN: "UpdateProfilePhoto",
    CREATED_SUCCESSFULLY: "ProfileCreatedSuccessful",
    HOME_TAB_SCREEN: "HomeTab",
    HOME_STACK_SCREEN: "HomeStack",
    HOME_DRAWER_SCREEN: "HomeDrawer",
    HOME_MAIN_SCREEN: "HomeMain",
    PRODUCTS_TAB_SCREEN: "ProductsTab",
    PRODUCTS_STACK_SCREEN: "ProductsStack",
    PRODUCTS_DRAWER_SCREEN: "ProductsDrawer",
    PRODUCTS_MAIN_SCREEN: "ProductsMain",
    PROFILE_STACK_SCREEN: "ProfileStack",
    PROFILE_SCREEN: "Profile",
    EDIT_PROFILE_SCREEN: "EditProfile",
    WISHLIST_SCREEN: "Wishlist",
    CONTACTUS_SCREEN: "ContactUs",
    NOTIFICATION_SCREEN: "Notification",
    PRODUCT_DETAILS_SCREEN: "ProductDetails",
    Home_SCREEN: "Home",
    Products_SCREEN: "Productslist",
    SEARCH_RESULTS_SCREEN: "SearchResults",
    OFFERS_AND_PROMO_SCREEN: "Offers And Promo",
    PRIVACY_POLICY_SCREEN: "Privacy Policy",
    SECURITY_SCREEN: "Security",
    CART_STACK_SCREEN: "CartStack",
    CART_SCREEN: "Cart",
    CHECKOUT_DELIVERY_SCREEN: "CheckoutDelivery",
    CHECKOUT_PAYMENT_SCREEN: "CheckoutPayment",
    ORDER_STACK_SCREEN: "OrderStack",
    ORDERS_SCREEN: "Orders",
    ORDER_TRACK_SCREEN: "OrderTrack",
    RATING_SCREEN: "OrderRating",
}